# Generated by Django 3.0 on 2022-03-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0003_auto_20220329_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='wishlist_id',
            new_name='wishlist',
        ),
    ]
