# Generated by Django 3.0 on 2022-03-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0004_auto_20220329_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='wishlist',
        ),
    ]
