# Generated by Django 3.0 on 2022-03-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0009_auto_20220331_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default='Enter Product Price', max_length=100),
        ),
    ]
