# Generated by Django 3.0 on 2022-03-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0011_auto_20220331_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addresss',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
