# Generated by Django 3.0 on 2022-03-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0014_remove_order_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderItems',
        ),
    ]
