# Generated by Django 3.0 on 2022-03-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0015_auto_20220331_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default='Enter Product Price'),
        ),
    ]
