# Generated by Django 3.0 on 2022-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0016_auto_20220331_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
