# Generated by Django 3.0 on 2022-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0017_auto_20220331_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
