# Generated by Django 3.0 on 2022-04-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0019_auto_20220331_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item',
            field=models.ManyToManyField(to='ecommerce_site.Cart'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
