# Generated by Django 3.0 on 2022-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0023_subscribedusers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
