# Generated by Django 3.0 on 2022-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0024_auto_20220404_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
